name: Release on push on master branch
 
on:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release-on-push-on-master-branch:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      
      - name: DryRun Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          dry_run: true
      
      - name: Install .Net dependencies
        run: dotnet restore ./
 
      - name: Run build
        run: dotnet build ./  --configuration Release --no-restore
 
      - name: Run publish SSI.FCTrading.Client
        run: |
          cd SSI.FCTrading.Client
          dotnet publish SSI.FCTrading.Client.csproj -c Release -o ../out-linux64/SSI.FCTrading.Client -r linux-x64 --self-contained true /p:UseAppHost=true /p:Version=${{ steps.semantic.outputs.new_release_version  }}
          dotnet publish SSI.FCTrading.Client.csproj -c Release -o ../out-win64/SSI.FCTrading.Client -r win-x64 --self-contained true /p:UseAppHost=true /p:Version=${{ steps.semantic.outputs.new_release_version  }}
      - name: Run publish SSI.FCTrading.ClientExample
        run: |
          cd SSI.FCTrading.ClientExample
          dotnet publish SSI.FCTrading.ClientExample.csproj -c Release -o ../out-linux64/SSI.FCTrading.ClientExample -r linux-x64 --self-contained true /p:UseAppHost=true /p:Version=${{ steps.semantic.outputs.new_release_version  }}
          dotnet publish SSI.FCTrading.ClientExample.csproj -c Release -o ../out-win64/SSI.FCTrading.ClientExample -r win-x64 --self-contained true /p:UseAppHost=true /p:Version=${{ steps.semantic.outputs.new_release_version  }}
 
 
      - name: ZIP my-project directory
        run: |
          mkdir target
          zip -r target/win64.zip out-win64
          zip -r target/linux64.zip out-linux64
 
      - name: Semantic Release
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: cycjimmy/semantic-release-action@v3